# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule:
    - cron: "0 0/12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: metrics1
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

          # Options
          filename: metrics1.svg
          user: soranjiro
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 10
          plugin_languages_sections: recently-used, most-used
          plugin_languages_ignored: html
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365
          commits_authoring: ${{ secrets.PERSONAL_EMAIL }}, soranjiro

      - name: metrics2
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

          # Options
          filename: metrics2.svg
          user: soranjiro
          base: ""
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, languages, languages-graphs
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
